[package]
name = "ptybug"
version = "0.1.0"
edition = "2024"

[dependencies]
crossbeam = "0.8.4"
portable-pty = { version = "0.8.1", features = ["serde_support"] }
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
