name: ci

on:
  push:
    branches: ["master", "dev"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]

    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable

      # needed for the test
      - name: Intall Deno
        uses: denoland/setup-deno@v2

      - uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      # - run: cargo build
      - name: Run cargo test with timeout (Linux/macOS)
        if: runner.os != 'Windows'
        run: timeout 600 cargo test -- --nocapture

      - name: Run cargo test with timeout (Windows)
        if: runner.os == 'Windows'
        run: |
          $p = Start-Process cargo -ArgumentList 'test -- --nocapture' -PassThru
          if (-not $p.WaitForExit(600000)) { # 600000 ms = 10 min
            Write-Host "Timeout reached, killing process"
            Stop-Process -Id $p.Id
            exit 1
          }
        shell: pwsh
